### PR TITLE
Fixed issue converting an empty object to a nullable numeric property

### PR DESCRIPTION
**Pull request by bfutrell70**
Also added an example to actually pull all deals from HubSpot.  Given some HubSpot accounts could have a large number of deals the example has been commented.

### CODE REVIEW

**Comment by clarkd** [comment]
Thanks for this! I want to take a quick look at the nullable stuff as I'm sure we were using nullables already (especially on some of our custom models). Is it specific types that were causing an issue?

**Comment by bfutrell70** [comment]
I made the error of committing to my fork's master branch - my apologies.  

Added API calls to retrieve recently created and modified deals.

**Comment by bfutrell70** [comment]
Reverted the addition of recently modified/created deals - I'll add it to the next PR.

**Comment by clarkd** [comment]
Just had a look at this and I can't seem to reproduce the original issue - do you have a specific set of steps or test case?

If I set the amount field to nullable, I can create a deal with no amount and GetById the same deal back etc without an issue.

**Comment by bfutrell70** [comment]
Reverting my changes to the RequestDataConvert's ConvertSingleEntity method but leaving the Deal amount as nullable I created a deal in HubSpot with the following information:

- Deal Name (anything can go here)
- Deal Stage (Closed Won, but anything can go here)
- HubSpot Owner

I assigned the deal to a company and a contact.

Using the ID created from that I can attempt to retrieve a deal ID with the newly created deal's ID and I can reproduce the error on the following line in ConvertSingleEntity:

var value = dynamicValue.GetType() == t ? dynamicValue : Convert.ChangeType(dynamicValue, t);

Here is what is showing for the Amount property at the time of the error:

amount properties

**Comment by clarkd** [comment]
Hey @bfutrell70, I've managed to repro the issue now.

Interestingly, this snippet doesn't cause the issue to occur - it looks like there's a difference between creating a deal via the API vs UI. Will investigate a little further and might raise an issue with the HubSpot team.

**Comment by clarkd** [comment]
Added a couple of commits, but will merge shortly :)

**Comment by clarkd** [comment]
Fixes #8

**Comment by bfutrell70** [comment]
Thanks!

In the case of most of the deals I was retrieving they were created by sales reps in the UI.  Currently there are no API-created deals in our data but I'm working on a program to add new ones.

**Comment by clarkd** [comment]
@bfutrell70, that makes sense - we're fairly new to HubSpot and the whole reason I built the wrapper was to migrate from a legacy CRM so all of ours were created by the API! 

On a side note, thanks for all your recent efforts with this project - it's been great to see people picking it up and fixing issues!

**Comment by clarkd** [comment]
FYI @bfutrell70, HubSpot are saying they've now fixed this issue so I'll take a look and see if we need to revert anything.

https://integrate.hubspot.com/t/api-vs-ui-difference-when-creating-a-deal/9816/2

**Comment by bfutrell70** [comment]
Nice to know - maybe they can also change recently created/modified deals
to return the list of deals in the property 'deals', rendering my changes
moot.  I don't expect it but one can dream. :)

I apologize for not seeing your prior email back in May - it's been rather
busy over here in Creedmoor, NC.  I had working code to pull data from
HubSpot before finding your project but your code was so much better - I
learned a lot from going through it.

**Pull request merged**
