### PR TITLE
Upgraded to .Net Standard 2.0. Added support for DateTime / DateTimeOffset datatypes for properties

### PR DESCRIPTION
**Pull request by nick-goloborodko**

### CODE REVIEW

**Comment by clarkd** [comment]
Do you know if it would be possible to target both .NET Framework 4.6.1 as well as .NET Standard? We were currently targeting two versions of .NET Framework so it would be nice to keep those.

**Comment by nick-goloborodko** [comment]
.NET Standard 2.0 library should work just fine with .NET 4.6.1 framework - as well as a whole lot of other platforms. I may need to do a bit more reading regarding targeting multiple frameworks

**Comment by clarkd** [comment]
Ah, yes I think you're right. I'll do some digging too and test a few applications that we're using this with for compatibility!

**Comment by Psypher9** [comment]
Is everything still looking good for this PR to go through? My team and I are looking to contribute, but the projects we need this Client SDK for require .NET Standard 2.0. So I'm just curious.

**Comment by clarkd** [comment]
My comment from June seems like a world away - so apologies for dropping the ball on this. We're gearing up for a major product release so thinks are a bit hectic right now.

**Comment by Psypher9** [comment]
Unfortunately, these changes are no longer compatible as the `RequestDataSerializer` is in the process of being deprecated entirely. Still, @nick-goloborodko thank you for your PR!

**Pull request closed without merging**
